version: "3"
services:
  mongodb:
    image: mongo:4.4.18
    restart: always
    container_name: mongodb-labs
    env_file:
      - ./server/.env
    ports:
      - 9000:27017
    volumes:
      - mongodb-booking-labs:/data/db

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 9001:8081
    depends_on:
      - mongodb

  booking-labs-server:
    build: ./server
    container_name: booking-labs-server
    env_file:
      - ./server/.env
    ports:
      - 8081:8081
    volumes:
      - ./server:/app
    depends_on:
      - mongodb

  booking-labs-client:
    build: ./client
    container_name: booking-labs-client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    depends_on:
      - booking-labs-server

volumes:
  mongodb-booking-labs:
