version: "3"
services:
  mongodb:
    image: mongo:4.4.18
    restart: always
    container_name: mongodb-labs
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 9000:27017
    volumes:
      - mongodb-booking-labs:/data/db

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 9001:8081
    depends_on:
      - mongodb

  booking-labs-server:
    build: ./server
    container_name: booking-labs-server
    ports:
      - 8081:8081
    environment:
      MONGO_CONNECTION_STRING: mongodb://root:root@mongodb:27017/booking-labs?authSource=admin
    volumes:
      - ./server:/app

  booking-labs-client:
    build: ./client
    container_name: booking-labs-client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app

volumes:
  mongodb-booking-labs:
